In [2]:
import pandas as pd

In [1]:
df1 = pd.read_csv('midterm_data(1)_김재용_2019011033.csv')

NameError: name 'pd' is not defined

In [25]:
df1

,기준일,서울,인천,경기,강원,충북,충남,대전,세종,경북,대구,전북,전남,광주,경남,부산,울산,제주,합계
0,2022-03-01,43206,14134,45891,8652,9683,11532,8595,2069,12318,17584,8404,9978,6015,14371,15330,3789,26702,258253
1,2022-02-01,41693,13179,41266,8179,8664,10525,7902,1902,11540,17091,7456,9203,5652,13536,13805,3405,26184,241182
2,2022-01-01,41140,12942,40239,8042,8184,10015,7675,1879,11269,16169,7389,8837,5204,12725,12501,3180,25580,232970
3,2021-12-01,40564,12820,39958,7946,8194,9991,7701,1859,11240,16185,7365,8708,5194,12606,12375,3166,25571,231443
4,2021-11-01,38840,11775,38563,7231,7731,9836,7737,1717,10870,16083,7147,8042,4978,12122,11766,3149,25381,222968
5,2021-10-01,35067,11295,37084,6786,7362,9480,7700,1680,10373,15753,6733,7826,4806,11199,10939,3184,24410,211677
6,2021-09-01,33434,10543,35385,6266,6801,8847,7134,1627,10013,15122,6286,7574,4722,10274,10480,3167,23845,201520
7,2021-08-01,31220,9370,33832,5929,6414,8426,6652,1509,9683,14632,5826,7211,4478,9730,9525,3038,23590,191065
8,2021-07-01,29325,8446,31820,5485,5934,8042,6143,1437,9171,14226,5466,6956,4242,9244,8824,2943,23262,180966
9,2021-06-01,28752,7790,30030,5200,5480,7254,5836,1404,8676,13974,5104,6643,4081,8685,8503,2897,22838,173147
10,2021-05-01,27013,6708,26944,4750,4952,6588,5222,1353,8118,13472,4432,6222,3813,7867,7515,2734,22148,159851
11,2021-04-01,25581,6312,24841,4460,4781,6269,4995,1317,7773,13142,4054,6001,3593,7474,6821,2599,21978,151991
12,2021-03-01,24918,6106,23887,4280,4688,5946,4885,1295,7588,13041,3596,5773,3504,7220,6600,2527,21832,147686
13,2021-02-01,23381,5517,21100,4086,4338,5575,4462,1186,7149,12846,3363,5415,3200,6552,5512,2284,21297,137263
14,2021-01-01,23441,5428,20670,4076,3897,5562,4463,1157,7066,12557,3360,5251,3210,6369,5409,2269,21206,135391
15,2020-12-01,23393,5366,20477,4078,3883,5489,4469,1148,7051,12630,3323,5223,3210,6308,5355,2274,21285,134962
16,2020-11-01,23052,4999,19903,3810,3794,5157,4415,1127,6753,12570,3269,5055,3162,6137,5210,2249,21261,131923
17,2020-10-01,22676,4729,19332,3567,3662,4878,4197,1106,6314,12550,3130,4896,3158,5924,4696,2221,21222,128258
18,2020-09-01,22118,4639,18512,3340,3467,4547,4083,1100,5816,12552,2977,4759,3151,5617,4420,2204,21107,124409
19,2020-08-01,20997,4204,17197,3091,3319,4252,3338,1076,5400,12468,2906,4576,3046,5003,4320,2142,20699,118034
20,2020-07-01,20003,3940,16508,3025,3268,4087,3204,1057,5192,12454,2848,4444,2962,4886,4216,2119,20105,114318
21,2020-06-01,19411,3741,15946,2952,3199,3920,3126,1044,4980,12356,2745,4323,2844,4805,4100,2110,19705,111307
22,2020-05-01,18098,3402,14876,2839,3077,3701,3001,1030,4818,12160,2561,4125,2745,4568,3936,1774,19388,106099
23,2020-04-01,17622,3345,14546,2753,2939,3560,2962,1024,4682,11878,2467,4067,2710,4432,3883,1738,19092,103700
24,2020-03-01,17172,3270,14100,2640,2617,3281,2865,1017,4441,11641,2270,3893,2660,4295,3624,1650,18793,100229
25,2020-02-01,16438,2791,12510,2459,2457,2928,2625,933,4161,11275,1920,3346,2489,3822,3270,1464,18684,93572
26,2020-01-01,15353,2660,11809,2448,2427,2848,2618,911,4071,11274,1872,3326,2479,3634,3223,1441,18307,90701
27,2019-12-01,14952,2598,11750,2445,2412,2841,2555,903,4051,11313,1841,3326,2464,3626,3216,1447,18178,89918
28,2019-10-01,12711,2412,11035,2385,2271,2649,2361,867,3832,9733,1804,3278,2341,3592,2645,1198,17933,83047
29,2019-09-01,12389,2322,10657,2339,2144,2551,2303,857,3670,9403,1752,3259,2283,3458,2567,1169,17779,80902
30,2019-08-01,12050,2210,10304,2236,2106,2490,2224,826,3563,9053,1700,3122,2213,3392,2489,1123,17559,78660
31,2019-07-01,11764,2132,9877,2114,2074,2421,2117,811,3409,8656,1641,3077,2140,3258,2410,1079,17352,76332
32,2019-06-01,11082,1985,9267,1945,1973,2308,1937,800,3159,8307,1586,2979,2024,3108,2234,1019,17101,72814
33,2019-05-01,10613,1842,8549,1833,1882,2246,1781,728,2971,7964,1490,2817,1870,3005,2085,959,16588,69223
34,2019-04-01,10175,1686,7872,1727,1695,2051,1616,642,2763,7475,1418,2687,1736,2783,1906,927,16066,65225
35,2019-03-01,9934,1499,7290,1567,1377,1559,1463,535,2404,7140,1196,2514,1587,2602,1786,902,15597,60952
36,2019-02-01,9647,1341,6579,1423,1216,1161,1358,414,2043,6927,1017,1999,1462,2211,1602,864,15268,56532
37,2019-01-01,9571,1298,6493,1393,1205,1142,1360,402,2017,6885,1005,1997,1446,2123,1589,862,15297,56085

In [ ]:
/*csv랑 xlsx는 불러오는 함수가 다름!!!*/